// open_mahjong_web/client/src/views/game2d/SceneAppearancePanel.vue
<template>
  <div class="scene-appearance-panel">
    <div class="scene-appearance-panel__header">
      <h3 class="scene-appearance-panel__title">设置</h3>
      <button type="button" class="scene-appearance-panel__ghost-button" @click="$emit('reset')">重置</button>
    </div>

    <label class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">牌桌内背景</span>
      <input type="color" :value="appearance.backgroundColorTable" @input="emitColor('table-color', $event)">
    </label>

    <label class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">牌桌外背景</span>
      <input type="color" :value="appearance.backgroundColorOutside" @input="emitColor('outside-color', $event)">
    </label>

    <label class="scene-appearance-panel__field scene-appearance-panel__field--toggle">
      <span class="scene-appearance-panel__label">启用本地图像</span>
      <input
        type="checkbox"
        :checked="appearance.backgroundImageEnabled"
        @change="$emit('image-enabled', $event.target.checked)"
      >
    </label>

    <div class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">图像不透明度</span>
      <div class="scene-appearance-panel__range-row">
        <input
          class="scene-appearance-panel__range"
          type="range"
          min="0"
          max="100"
          :value="Math.round(appearance.backgroundImageAlpha * 100)"
          :disabled="!backgroundImageName"
          @input="$emit('image-alpha', Number($event.target.value) / 100)"
        >
        <span class="scene-appearance-panel__value">{{ Math.round(appearance.backgroundImageAlpha * 100) }}%</span>
      </div>
    </div>

    <div class="scene-appearance-panel__button-row">
      <button type="button" class="scene-appearance-panel__button" @click="fileInput?.click()">选择图片</button>
      <button
        type="button"
        class="scene-appearance-panel__button"
        :disabled="!backgroundImageName"
        @click="$emit('image-cleared')"
      >
        移除图片
      </button>
      <input ref="fileInput" type="file" accept="image/*" hidden @change="selectImage">
    </div>

    <div class="scene-appearance-panel__hint">
      {{ backgroundImageLoading ? '正在读取已保存图片…' : backgroundImageName ? `已保存图片：${backgroundImageName}` : '未选择背景图片' }}
    </div>

    <div class="scene-appearance-panel__section">
      <div class="scene-appearance-panel__section-header">
        <span class="scene-appearance-panel__label">牌背覆盖色</span>
        <button type="button" class="scene-appearance-panel__ghost-button" @click="$emit('add-cover-color')">添加颜色</button>
      </div>
      <div class="scene-appearance-panel__swatch-list">
        <div v-for="(color, index) in appearance.tileCoverColors" :key="index" class="scene-appearance-panel__swatch-row">
          <input type="color" :value="color" @input="emitCoverColor(index, $event)">
          <span class="scene-appearance-panel__swatch-code">{{ color.toUpperCase() }}</span>
          <button
            type="button"
            class="scene-appearance-panel__ghost-button"
            :disabled="appearance.tileCoverColors.length <= 1"
            @click="$emit('remove-cover-color', index)"
          >
            删除
          </button>
        </div>
      </div>
    </div>

    <label class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">补花区底框</span>
      <select
        class="scene-appearance-panel__select"
        :value="appearance.flowerAreaDisplay"
        @change="$emit('flower-area-display', $event.target.value)"
      >
        <option value="always">始终显示</option>
        <option value="when-present">有花牌时显示</option>
        <option value="never">固定不显示</option>
      </select>
    </label>

    <label class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">补花区颜色</span>
      <input
        type="color"
        :value="appearance.flowerAreaColor"
        @input="$emit('flower-area-color', $event.target.value)"
      >
    </label>

    <div class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">补花区透明度</span>
      <div class="scene-appearance-panel__range-row">
        <input
          class="scene-appearance-panel__range"
          type="range"
          min="0"
          max="100"
          :value="Math.round(appearance.flowerAreaAlpha * 100)"
          @input="$emit('flower-area-alpha', Number($event.target.value) / 100)"
        >
        <span class="scene-appearance-panel__value">{{ Math.round(appearance.flowerAreaAlpha * 100) }}%</span>
      </div>
    </div>

    <label class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">牌面样式</span>
      <select
        class="scene-appearance-panel__select"
        :value="appearance.tileFaceTheme"
        @change="$emit('tile-face-theme', $event.target.value)"
      >
        <option value="regular">标准白色</option>
        <option value="black">FluffyStuff 黑色</option>
      </select>
    </label>

    <label class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">花牌样式</span>
      <select
        class="scene-appearance-panel__select"
        :value="appearance.flowerFaceTheme"
        @change="$emit('flower-face-theme', $event.target.value)"
      >
        <option value="flat">当前平面花牌</option>
        <option value="unity">Unity 原版花牌</option>
      </select>
    </label>

    <div class="scene-appearance-panel__field">
      <span class="scene-appearance-panel__label">音量</span>
      <div class="scene-appearance-panel__range-row">
        <input
          class="scene-appearance-panel__range"
          type="range"
          min="0"
          max="100"
          :value="Math.round(volume * 100)"
          @input="$emit('volume', Number($event.target.value) / 100)"
        >
        <span class="scene-appearance-panel__value">{{ Math.round(volume * 100) }}%</span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

defineProps({
  appearance: { type: Object, required: true },
  backgroundImageName: { type: String, default: null },
  backgroundImageLoading: { type: Boolean, default: false },
  volume: { type: Number, required: true },
})

const emit = defineEmits([
  'reset', 'table-color', 'outside-color', 'image-enabled', 'image-alpha',
  'image-selected', 'image-cleared', 'cover-color', 'add-cover-color',
  'remove-cover-color', 'flower-area-display', 'flower-area-color',
  'flower-area-alpha', 'tile-face-theme', 'flower-face-theme', 'volume',
])
const fileInput = ref(null)

function emitColor(name, event) {
  emit(name, event.target.value)
}

function emitCoverColor(index, event) {
  emit('cover-color', index, event.target.value)
}

function selectImage(event) {
  const file = event.target.files?.[0]
  if (file) emit('image-selected', file)
  event.target.value = ''
}
</script>

// open_mahjong_2d/src/components/SceneAppearancePanel.tsx
import { useRef } from 'react'

import type { SceneAppearanceSettings } from '../lib/sceneAppearance'

type SceneAppearancePanelProps = {
  title: string
  appearance: SceneAppearanceSettings
  backgroundImageName: string | null
  backgroundImageLoading: boolean
  volume: number
  onVolumeChange: (volume: number) => void
  onBackgroundColorTableChange: (color: string) => void
  onBackgroundColorOutsideChange: (color: string) => void
  onBackgroundImageEnabledChange: (enabled: boolean) => void
  onBackgroundImageAlphaChange: (alpha: number) => void
  onBackgroundImageSelected: (file: File) => void | Promise<void>
  onBackgroundImageCleared: () => void | Promise<void>
  onTileCoverColorChange: (index: number, color: string) => void
  onAddTileCoverColor: () => void
  onRemoveTileCoverColor: (index: number) => void
  onReset: () => void | Promise<void>
}

export default function SceneAppearancePanel({
  title,
  appearance,
  backgroundImageName,
  backgroundImageLoading,
  volume,
  onVolumeChange,
  onBackgroundColorTableChange,
  onBackgroundColorOutsideChange,
  onBackgroundImageEnabledChange,
  onBackgroundImageAlphaChange,
  onBackgroundImageSelected,
  onBackgroundImageCleared,
  onTileCoverColorChange,
  onAddTileCoverColor,
  onRemoveTileCoverColor,
  onReset,
}: SceneAppearancePanelProps) {
  const fileInputRef = useRef<HTMLInputElement | null>(null)

  return (
    <div className="scene-appearance-panel">
      <div className="scene-appearance-panel__header">
        <h3 className="scene-appearance-panel__title">{title}</h3>
        <button
          type="button"
          className="scene-appearance-panel__ghost-button"
          onClick={() => { void onReset() }}
        >
          重置
        </button>
      </div>

      <label className="scene-appearance-panel__field">
        <span className="scene-appearance-panel__label">牌桌内背景</span>
        <input
          type="color"
          value={appearance.backgroundColorTable}
          onChange={(event) => onBackgroundColorTableChange(event.target.value)}
        />
      </label>

      <label className="scene-appearance-panel__field">
        <span className="scene-appearance-panel__label">牌桌外背景</span>
        <input
          type="color"
          value={appearance.backgroundColorOutside}
          onChange={(event) => onBackgroundColorOutsideChange(event.target.value)}
        />
      </label>

      <label className="scene-appearance-panel__field scene-appearance-panel__field--toggle">
        <span className="scene-appearance-panel__label">启用本地图像</span>
        <input
          type="checkbox"
          checked={appearance.backgroundImageEnabled}
          onChange={(event) => onBackgroundImageEnabledChange(event.target.checked)}
        />
      </label>

      <div className="scene-appearance-panel__field">
        <span className="scene-appearance-panel__label">图像不透明度</span>
        <div className="scene-appearance-panel__range-row">
          <input
            className="scene-appearance-panel__range"
            type="range"
            min={0}
            max={100}
            value={Math.round(appearance.backgroundImageAlpha * 100)}
            onChange={(event) => onBackgroundImageAlphaChange(Number(event.target.value) / 100)}
            disabled={!backgroundImageName}
          />
          <span className="scene-appearance-panel__value">{Math.round(appearance.backgroundImageAlpha * 100)}%</span>
        </div>
      </div>

      <div className="scene-appearance-panel__button-row">
        <button
          type="button"
          className="scene-appearance-panel__button"
          onClick={() => fileInputRef.current?.click()}
        >
          选择图片
        </button>
        <button
          type="button"
          className="scene-appearance-panel__button"
          onClick={() => { void onBackgroundImageCleared() }}
          disabled={!backgroundImageName}
        >
          移除图片
        </button>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          hidden
          onChange={(event) => {
            const file = event.target.files?.[0]
            if (file) {
              void onBackgroundImageSelected(file)
            }
            event.target.value = ''
          }}
        />
      </div>

      <div className="scene-appearance-panel__hint">
        {backgroundImageLoading
          ? '正在读取已保存图片…'
          : backgroundImageName
            ? `已保存图片：${backgroundImageName}`
            : '未选择背景图片'}
      </div>

      <div className="scene-appearance-panel__section">
        <div className="scene-appearance-panel__section-header">
          <span className="scene-appearance-panel__label">牌背覆盖色</span>
          <button
            type="button"
            className="scene-appearance-panel__ghost-button"
            onClick={onAddTileCoverColor}
          >
            添加颜色
          </button>
        </div>
        <div className="scene-appearance-panel__swatch-list">
          {appearance.tileCoverColors.map((color, index) => (
            <div className="scene-appearance-panel__swatch-row" key={index}>
              <input
                type="color"
                value={color}
                onChange={(event) => onTileCoverColorChange(index, event.target.value)}
              />
              <span className="scene-appearance-panel__swatch-code">{color.toUpperCase()}</span>
              <button
                type="button"
                className="scene-appearance-panel__ghost-button"
                onClick={() => onRemoveTileCoverColor(index)}
                disabled={appearance.tileCoverColors.length <= 1}
              >
                删除
              </button>
            </div>
          ))}
        </div>
      </div>

      <div className="scene-appearance-panel__field">
        <span className="scene-appearance-panel__label">音量</span>
        <div className="scene-appearance-panel__range-row">
          <input
            className="scene-appearance-panel__range"
            type="range"
            min={0}
            max={100}
            value={Math.round(volume * 100)}
            onChange={(event) => onVolumeChange(Number(event.target.value) / 100)}
          />
          <span className="scene-appearance-panel__value">{Math.round(volume * 100)}%</span>
        </div>
      </div>

    </div>
  )
}
